### ISSUE TITLE
to fork or not to fork?

### ISSUE THREAD

**Issue by bbortt** [bbortt/mat-datetimepicker#1]
@DenysVuika I am not sure if the advantages of an (active) fork will pay out.

Facts:
* **kuhnroyl** seems not to be very active, having only 30 commits in the last year
  * he seems to ignore most of his GitHub emails
  * he does not answer any issues nor pull-requests
* project settings are kind of locked
  * I have access to repository and npmjs but cannot edit anything nor add new contributors
* however we have "full-control" over Travis-Ci

Things to consider:
* we might need a rebranding when publishing the fork
 * we might consider a relicensing too
* he won't archive the original project any time soon
* redirecting people will be difficult (with `README.md` only)
  * we could maybe include only the `README.md` into the `master` without any code - that makes it more obvious
* we might still have to support "legacy" `angular/angular` versions (and therefore deal with the old branches)

What do you think about it?

**Comment by DenysVuika** [comment]
Hard to say. If the project keeps being unmaintained, everyone will start forking and using own copies.
